name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-11", ubuntu-20.04, "windows-latest"]
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: x64
    - name: Install requirements
      run: |
        sudo apt-get -y update
        sudo apt-get install -y cmake llvm-9 clang-9 autoconf automake \
        libtool build-essential curl git lldb-6.0 liblldb-6.0-dev
        python -m pip install -U pip wheel setuptools
        python -m pip install scikit-build
  
    - name: Create Build Environment
      run: python setup.py develop
    
    - name: Run pytest
      run: |
       python -m pip install pytest
       python -m pytest tests

    - name: Run benchmarks
      run: |
       python -m pip install rich
       python benchmarks/suite.py