name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-11", ubuntu-20.04, "windows-latest"]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
        architecture: x64
    - name: Get latest CMake and ninja
      # Using 'latest' branch, the most recent CMake and ninja are installed.
      uses: lukka/get-cmake@latest
    - uses: actions/checkout@v3
    - name: Install requirements and package
      run: |
        python -m pip install -U scikit-build
        python -m pip install -v .

    - name: Run pytest
      run: |
       python -m pip install pytest
       python -m pytest tests

    - name: Run pytest with repeat
      run: | 
       python -m pip install pytest-repeat
       python -m pytest --count=10 tests

    - name: Run benchmarks
      if: matrix.python_version == '3.10'
      run: |
       python -m pip install richbench
       richbench benchmarks/

    - name: Run Coverage
      if: ${{ matrix.os == 'ubuntu-20.04' && matrix.python_version == '3.10' }}
      run: | 
        python setup.py build_ext --inplace --build-type Debug -DCOVERAGE=ON
        python -m pytest tests
    
    - uses: codecov/codecov-action@v2
      with:
        verbose: true
        gcov: true
        gcov_include: _skbuild/linux-x86_64-3.10/cmake-build/CMakeFiles/_picologging.dir/src/picologging/