name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-11", ubuntu-20.04, "windows-latest"]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
        architecture: x64
    - name: Get latest CMake and ninja
      # Using 'latest' branch, the most recent CMake and ninja are installed.
      uses: lukka/get-cmake@latest
    - name: Install requirements
      run: python -m pip install .[dev]
    
    - name: Run pytest
      run: |
       python -m pip install pytest
       python -m pytest tests

    - name: Run benchmarks
      run: |
       python -m pip install rich
       python benchmarks/suite.py